// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhcK2Uaa5yXHNXtaxFhdf_roSnpQ_1jd0',
    appId: '1:42337678794:web:d8d03034e34f24e46c4b33',
    messagingSenderId: '42337678794',
    projectId: 'api-s-project-10',
    authDomain: 'api-s-project-10.firebaseapp.com',
    databaseURL: 'https://api-s-project-10-default-rtdb.firebaseio.com',
    storageBucket: 'api-s-project-10.appspot.com',
    measurementId: 'G-D3NY80R61V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPMsFI1aJeW6dhebrL8JY7kb_1kLNW7-4',
    appId: '1:42337678794:android:7fc6a3231973b7286c4b33',
    messagingSenderId: '42337678794',
    projectId: 'api-s-project-10',
    databaseURL: 'https://api-s-project-10-default-rtdb.firebaseio.com',
    storageBucket: 'api-s-project-10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB97LQJpTLTvrccTnKqrihGBUGuVEBWILU',
    appId: '1:42337678794:ios:6fe00e085a572a956c4b33',
    messagingSenderId: '42337678794',
    projectId: 'api-s-project-10',
    databaseURL: 'https://api-s-project-10-default-rtdb.firebaseio.com',
    storageBucket: 'api-s-project-10.appspot.com',
    androidClientId: '42337678794-9vnbf4sg0qagu794970hudouc1fmo5m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceShoppers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB97LQJpTLTvrccTnKqrihGBUGuVEBWILU',
    appId: '1:42337678794:ios:725da3b61f0e54d06c4b33',
    messagingSenderId: '42337678794',
    projectId: 'api-s-project-10',
    databaseURL: 'https://api-s-project-10-default-rtdb.firebaseio.com',
    storageBucket: 'api-s-project-10.appspot.com',
    androidClientId: '42337678794-9vnbf4sg0qagu794970hudouc1fmo5m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceShoppers.RunnerTests',
  );
}
